// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2XysN_ybP9uNZT0SJ-DXfvHNlqbco-cg',
    appId: '1:792786193766:android:15c6e862b5bee5ce400ca7',
    messagingSenderId: '792786193766',
    projectId: 'dear-diary-v2-4b929',
    storageBucket: 'dear-diary-v2-4b929.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj5R9FbsbpInHV13Znv-WdyZwOU0QRcHE',
    appId: '1:792786193766:ios:d2e668b5a062f2b7400ca7',
    messagingSenderId: '792786193766',
    projectId: 'dear-diary-v2-4b929',
    storageBucket: 'dear-diary-v2-4b929.appspot.com',
    iosBundleId: 'com.example.dearDiaryv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj5R9FbsbpInHV13Znv-WdyZwOU0QRcHE',
    appId: '1:792786193766:ios:1e26805bb6e939a0400ca7',
    messagingSenderId: '792786193766',
    projectId: 'dear-diary-v2-4b929',
    storageBucket: 'dear-diary-v2-4b929.appspot.com',
    iosBundleId: 'com.example.dearDiaryv2.RunnerTests',
  );
}
